name: Setup

description: Setup Node.js, cache and install dependencies

inputs:
  git_bot_token:
    description: Git Bot token used to push to protected branches because github token can't
    required: false
  npm_token:
    description: NPM token used to publish packages
    required: false


runs:
  using: composite
  steps:

    - name: Checkout all commits
      uses: actions/checkout@v4
      with:
        token: ${{ inputs.git_bot_token || github.token }}
        fetch-depth: 0

            # Needed for nx affected command, it set the BASE and HEAD env variables
    - name: Derive appropriate SHAs for base and head for `nx affected` commands
      uses: nrwl/nx-set-shas@v3


    - name: Setup git user to "🤖 naxodev bot"
      shell: bash
      run: git config user.email "nacho@naxo.dev" && git config user.name "🤖 naxodev bot"


    - name: Determine Node.js version
      id: node_version
      shell: bash
      run: echo "node_version=$(cat .nvmrc)" >> $GITHUB_OUTPUT

    - uses: pnpm/action-setup@v2
      with:
        version: 9
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ steps.node_version.outputs.node_version }}
        cache: 'pnpm'
        registry-url: 'https://registry.npmjs.org'

    - name: Install dependencies
      shell: bash
      run: pnpm install
      
    - name: Configure PNPM registry
      shell: bash
      run: pnpm config set //registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}
      env:
        NODE_AUTH_TOKEN: ${{ inputs.npm_token }}
